package com.pilaf.tgl.api.enums;

public enum ParameterValueType {
    HEALTH, MANA, STRENGTH, VITALITY, DEXTERITY, PERSONALITY, WISDOM, PERCEPTION, KNOWLEDGE, SPEED, ENDURANCE, REFLEX, WILL, MAGICAL_RESISTANCE, ACTION_PONTS, DODGE, ATACK_DICE, ENERGY_LEVEL

}
